### ISSUE TITLE
Mejorar diseño

### ISSUE THREAD

**Issue by celsobessa** [Dejusticia/mota-evaluador-demo#5]
Que tal poner colores en los cajones similar a los grados. Es decir, en los criterios "Obligaciones Legales - Satisfactórias", el fondo poderia ser verde. En "Insatisfactórias", el fondo rojo, etc

**Comment by cbessadejusticia** [comment]
done and closed by https://github.com/Dejusticia/mota-evaluador-demo/commit/75cdafbdfb79ea42fb5e883b83a6e815d0e168f3
